application:
  name: zsf
  region: WestEast
  zone: shenzhen

discovery:
  etcd:
    endpoints: 127.0.0.1:2379
    username: root
    password: 123456

property:
  dynamic:
    etcd:
      endpoints: 127.0.0.1:2379
      username: root
      password: 123456

logger:
  loki:
    enabled: true
    orgId: local
    pushUrl: http://127.0.0.1:3100/loki/api/v1/push