# 工程配置
application:
  region: China
  zone: GuangdongShenzhen001
  name: my-runner

# grpc 配置
grpc:
  enabled: true
  lbPolicy: round_robin
  debug: false
  weight: 1
  port: 8099
  maxConnectionIdleSec: 600
  registry:
    enabled: true

# http 配置
http:
  enabled: true
  weight: 1
  port: 8091
  registry:
    enabled: true
  client:
    lbPolicy: round_robin

# consul配置
consul:
  address: 127.0.0.1:8500
  token: 5941da18-da21-d7a1-7c50-b69c10d43d0f

# 配置自动加载
property:
  enabled: true

# 服务发现
discovery:
  type: consul
  enabled: true

# prometheus server
prometheus:
  enabled: false
  port: 16005

# skywalking接入
skywalking:
  enabled: false
  serverAddr: 127.0.0.1:11800

pprof:
  enabled: false
  port: 18899


# consul agent -server -ui -bootstrap-expect=1 -data-dir=./consuldata -node=agent-1 -client=0.0.0.0 -datacenter=dc1 -bind=127.0.0.1 -rejoin -config-dir=./consuldata