logger:
  async:
    executorNum: 1
    enabled: true
    queueSize: 5000
    discardPolicy: abort
  kafka:
    enabled: false
    sasl: true
    username: test
    password: test
    hosts: 127.0.0.1:8642,127.0.0.1:7653
    topic: test-topic
  nsq:
    enabled: false
    host: 127.0.0.1:4105
    topic: log-wiwi-kalksj
    authSecret: xxx
  loki:
    enabled: true
    orgId: local
    pushUrl: http://127.0.0.1:3100/loki/api/v1/push

https:
  certFile: zsh.rsa.ca
  keyFile: zsh.rsa