# 工程配置
application:
  region: China
  zone: GuangdongShenzhen001
  name: my-runner

# grpc 配置
grpc:
  enabled: true
  lbPolicy: round_robin
  debug: false
  port: 8099
  weight: 1
  maxConnectionIdleSec: 600
  registry:
    enabled: true

# http 配置
http:
  enabled: true
  port: 8011
  weight: 1
  registry:
    enabled: true
  client:
    lbPolicy: round_robin

# 服务发现 type = etcd or static
discovery:
  type: etcd

registry:
  type: consul

# prometheus server
prometheus:
  enabled: true
  port: 16005

# skywalking接入
skywalking:
  enabled: false
  serverAddr: 127.0.0.1:11800

pprof:
  enabled: false
  port: 18899

xorm:
  dataSourceName: root:root@tcp(127.0.0.1:3306)/xxx?charset=utf8
  showSql: true

actuator:
  enabled: true

httptask:
  token: 123

etcd:
  username: xxxx
  password: xxxx
  hosts: 127.0.0.1:8080,127.0.0.1:8001

# git tag -a "v1.0.1" -m "beta"
# git push origin master --tags