application:
  name: zall
  region: WestEast
  zone: shenzhen

discovery:
  etcd:
    endpoints: 127.0.0.1:2379
    username: root
    password: 123456

property:
  dynamic:
    etcd:
      endpoints: 127.0.0.1:2379
      username: root
      password: 123456